### ISSUE TITLE
indy-sdk tutorial 

### ISSUE THREAD

**Issue by nekia** [nekia/100-days-of-code#1]
I'll output here about my activity log for the following tutorials.
https://github.com/hyperledger/indy-sdk/blob/master/README.md#how-to-tutorials

**Comment by nekia** [comment]
Write a DID and Query Its Verkey with Rust
https://github.com/hyperledger/indy-sdk/blob/master/docs/how-tos/write-did-and-query-verkey/README.md

**Comment by nekia** [comment]
**Issue**
Link for template.rs is broken
https://github.com/hyperledger/indy-sdk/blob/master/docs/how-tos/write-did-and-query-verkey/rust/README.md#step-1

**Comment by nekia** [comment]
Done installation of libindy

**Comment by nekia** [comment]
Done build of indy-pool container image

**Comment by nekia** [comment]
Succeeded to build, but failed to open pool ledger newly

**Comment by nekia** [comment]
There were 2 reasons why failed to open pool ledger:

- indy-pool is not running
I missed starting indy-pool container.

- The default pool_name ( `pool` ) is bad
It seems to be duplicate with some system reserved things. After changing to `poolpool`, it works without any errors!
```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/write-did-and-query-verkey`
1. Creating a new local pool ledger configuration that can be used later to connect pool nodes
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndyError { error_code: PoolLedgerConfigAlreadyExistsError, message: "Error: Pool ledger config already exists\n  Caused by: Pool ledger config file with name \"pool\" already exists\n", indy_backtrace: Some("stack backtrace:\n   0: <unknown> (0x7fcfa53f603f)\n   1: <unknown> (0x7fcfa53f5bdf)\n   2: <unknown> (0x7fcfa4db572f)\n   3: <unknown> (0x7fcfa509bf42)\n   4: <unknown> (0x7fcfa4fd7045)\n   5: <unknown> (0x7fcfa4d4236c)\n   6: <unknown> (0x7fcfa54287e9)\n   7: <unknown> (0x7fcfa4d132bc)\n   8: <unknown> (0x7fcfa541c6ed)\n   9: start_thread (0x7fcfa45a96da)\n  10: __clone (0x7fcfa40ba88e)\n  11: <unknown> (0x0)") }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:798
  10: write_did_and_query_verkey::main
             at src/write-did-and-query-verkey.rs:52
  11: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by nekia** [comment]
All code for HowTos tutorials are committed below.
https://github.com/hyperledger/indy-agent.git
They shoud work without any errors.
